FROM node:16.12.0

# Create app directory
RUN mkdir -p /usr/src/web-detect-api
WORKDIR /usr/src/web-detect-api

# Install app dependencies
COPY package.json /usr/src/web-detect-api
RUN npm install

# Bundle app source
COPY . /usr/src/web-detect-api

# Build arguments
ARG NODE_VERSION=16.12.0

# Environment
ENV NODE_VERSION $NODE_VERSION